---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blacksyrius.ci.com
  resources:
  - configmapmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blacksyrius.ci.com
  resources:
  - configmapmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - blacksyrius.ci.com
  resources:
  - configmapmanagers/status
  verbs:
  - get
  - patch
  - update
